// portfolio-website-react/src/components/viewAreas/examplesView/ExamplesView.js
import React from 'react';
import PastProjects from '../../projects/pastProjects/PastProjects';
import ReturnButton from '../../returnButton/ReturnButton';
import './ExamplesView.css'


const ExamplesView = () => {
    return (
        <div id="examples-view-main-div" className="content" >
            <div id="examples-div" className="content-background" >
                <p id="example-websites-title" className="section-title">Example Websites</p>
                <br />
                <p>Please click any of the below thumbnails to view the project on CodeSandBox.io.</p>
                <br />
                <div>
                    <PastProjects />
                </div>
            </div>
            <ReturnButton />
        </div>
    );
}

export default ExamplesView;

// portfolio-website-vue/src/views/ExamplesView.vue
<template>
    <div id="examples-view-main-div" class="content">
        <div id="examples-div" class="content-background">
            <p id="example-websites-title" class="section-title">Example Websites</p>
            <br>
            <p class="no-margin">Please click any of the below thumbnails to view full page image.</p>

            <br>
            
            <div>
                <completed-projects-thumbnail />
            </div>
        </div>

        <return-top-btn />

        <div>
            <full-screen-image />
        </div>
        
    </div>
</template>

<script>
import ReturnTopBtn from '../components/ReturnTopBtn.vue'
import CompletedProjectsThumbnail from '../components/CompletedProjectsThumbnail.vue'
import FullScreenImage from '../components/FullScreenImage.vue'
export default {
  components: { ReturnTopBtn, CompletedProjectsThumbnail, FullScreenImage },

}
</script>

<style>

#examples-view-main-div {
    display: flex;
    flex-direction: column;
    align-items: center;
    

}



</style>
